# -*- coding: utf-8 -*-
"""
/***************************************************************************
 fogo_florestal
                                 A QGIS plugin
 fogo_florestal
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-12-26
        git sha              : $Format:%H$
        copyright            : (C) 2025 by fogo_florestal
        email                : fogo_florestal
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QFileInfo
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog, QMessageBox, QDoubleSpinBox
from qgis.core import Qgis, QgsProject
from qgis import processing

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .fogo_florestal_dialog import fogo_florestalDialog
import os.path


import ee
import urllib.request




class fogo_florestal:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'fogo_florestal_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&fogo_florestal')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('fogo_florestal', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/fogo_florestal/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u''),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&fogo_florestal'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = fogo_florestalDialog()
            self.dlg.pushButton_2.clicked.connect(self.estatisticas)
            self.dlg.pushButton_4.clicked.connect(self.salvar)

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass



    def estatisticas(self):
        output = self.dlg.lineEdit_6.text().strip()


        """Calcula estatísticas básicas de área ardida (Monchique 2018)."""
        self._gee_init()
                        # ---------- 1) Autenticação e inicialização ----------
        aoi = ee.Geometry.Rectangle(
            [-8.75, 37.15, -8.25, 37.45],
            proj="EPSG:4326",
            geodesic=False)

        # ---------- 3) Datas (Monchique 2018) ----------
        pre_start, pre_end = "2018-06-02", "2018-08-02"
        post_start, post_end = "2018-08-11", "2018-10-15"

        # ---------- 5) Processamento ----------
        nbr_pre, n_pre = self._nbr_composite(aoi, pre_start, pre_end)
        nbr_post, n_post = self._nbr_composite(aoi, post_start, post_end)
        rgb_post = (
            ee.ImageCollection("COPERNICUS/S2_SR_HARMONIZED")
            .filterBounds(aoi)
            .filterDate(post_start, post_end)
            .filter(ee.Filter.lte("CLOUDY_PIXEL_PERCENTAGE", 60))
            .map(self._mask_s2_scl)
            .select(["B4", "B3", "B2"])
            .median()
            .clip(aoi)
        )

        dnbr = nbr_pre.subtract(nbr_post).rename("dNBR")

        threshold = 0.27
        burned = dnbr.gt(threshold).selfMask().rename("burned")
        boundaries = (
            ee.FeatureCollection("FAO/GAUL/2015/level2")
            .filterBounds(aoi)
        )
        outline = ee.Image().paint(boundaries, 1, 2).visualize(
            palette=["000000"]
        )

        # Área ardida (ha) dentro da AOI
        area_m2 = (
            burned.multiply(ee.Image.pixelArea())
            .reduceRegion(
                reducer=ee.Reducer.sum(),
                geometry=aoi,
                scale=20,  # 20 m é apropriado para B12 (SWIR2)
                maxPixels=1e13,
            )
            .getNumber("burned")
        )

        area_ha = area_m2.divide(10000)

        # ---------- 6) Output ----------
        n_pre_count = n_pre.getInfo()
        n_post_count = n_post.getInfo()
        burned_area_ha = float(area_ha.getInfo())
        print("=== Core test (Monchique 2018) ===")
        print("Pre window:", pre_start, "to", pre_end, "| images:", n_pre_count)
        print("Post window:", post_start, "to", post_end, "| images:", n_post_count)
        print("Threshold dNBR:", threshold)
        print("Burned area (ha):", burned_area_ha)

        # (Opcional) estatísticas rápidas do dNBR
        dnbr_stats = (
            dnbr.reduceRegion(
                reducer=ee.Reducer.minMax(),
                geometry=aoi,
                scale=20,
                maxPixels=1e13,
            ).getInfo()
        )
        print("dNBR min/max:", dnbr_stats)

        output_path = output or os.path.join(self.plugin_dir, "estatisticas.txt")
        output_dir = os.path.dirname(output_path) or self.plugin_dir
        base_name = os.path.splitext(os.path.basename(output_path))[0] or "estatisticas"
        report_lines = [
            "=== Estatisticas (Monchique 2018) ===",
            f"Pre window: {pre_start} to {pre_end} | images: {n_pre_count}",
            f"Post window: {post_start} to {post_end} | images: {n_post_count}",
            f"Threshold dNBR: {threshold}",
            f"Burned area (ha): {burned_area_ha}",
            f"dNBR min/max: {dnbr_stats}",
        ]
        with open(output_path, "w", encoding="utf-8") as handle:
            handle.write("\n".join(report_lines))

        dnbr_path = os.path.join(output_dir, f"{base_name}_dnbr.png")
        burned_path = os.path.join(output_dir, f"{base_name}_burned.png")

        vis_dnbr = {
            "min": -0.2,
            "max": 1.0,
            "palette": ["ffffff", "fff200", "ff8c00", "ff0000"],
        }
        vis_burned = {
            "min": 0,
            "max": 1,
            "palette": ["ff0000"],
        }
        vis_ref = {
            "bands": ["B4", "B3", "B2"],
            "min": 0.0,
            "max": 0.3,
        }
        dnbr_vis = dnbr.visualize(**vis_dnbr).blend(outline)
        burned_vis = burned.visualize(**vis_burned).blend(outline)

        def download_thumb(image, vis, output_file):
            params = {
                "region": aoi,
                "dimensions": 900,
                "crs": "EPSG:4326",
                "format": "png",
            }
            if vis:
                params["min"] = vis.get("min")
                params["max"] = vis.get("max")
                params["palette"] = vis.get("palette")
                if vis.get("bands"):
                    params["bands"] = vis.get("bands")
            url = image.getThumbURL(params)
            urllib.request.urlretrieve(url, output_file)

        download_thumb(dnbr_vis, None, dnbr_path)
        download_thumb(burned_vis, None, burned_path)
        ref_path = os.path.join(output_dir, f"{base_name}_referencia.png")
        download_thumb(rgb_post, vis_ref, ref_path)

        print("Relatorio salvo em:", output_path)


        self.iface.messageBar().pushMessage(
            "Success",
            "Output file and PNGs written at " + str(output_dir),
            level=Qgis.Success,
            duration=3
        )

        


    def salvar(self):
        filename, filter_string = QFileDialog.getSaveFileName(self.dlg, "Select Output file", "", '*.txt')
        if filename:
            self.dlg.lineEdit_6.setText(filename)

    def _gee_init(self):
        try:
            ee.Initialize(project='ee-vascosilvagames11')
        except Exception:
            ee.Authenticate()
            ee.Initialize(project='ee-vascosilvagames11')

    def _mask_s2_scl(self, img: ee.Image) -> ee.Image:
        scl = img.select("SCL")
        good = (
            scl.eq(4)
            .Or(scl.eq(5))
            .Or(scl.eq(6))
            .Or(scl.eq(7))
            .Or(scl.eq(11))
        )
        return img.updateMask(good).divide(10000)

    def _add_nbr(self, img: ee.Image) -> ee.Image:
        nbr = img.normalizedDifference(["B8", "B12"]).rename("NBR")
        return img.addBands(nbr)

    def _nbr_composite(self, aoi: ee.Geometry, start: str, end: str):
        col = (
            ee.ImageCollection("COPERNICUS/S2_SR_HARMONIZED")
            .filterBounds(aoi)
            .filterDate(start, end)
            .filter(ee.Filter.lte("CLOUDY_PIXEL_PERCENTAGE", 60))
            .map(self._mask_s2_scl)
            .map(self._add_nbr)
        )
        nbr = col.select("NBR").median().clip(aoi)
        return nbr, col.size()
